spring:
  application:
    name: legion-agent
  profiles:
    include:
      - tags

# server
server:
  port: 8802
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  connection-timeout: 5000
  servlet:
    context-path: /

# management
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      base-path: /exporter
      exposure:
        include: prometheus
    jmx:
      exposure:
        exclude: '*'
  server:
    port: 1${server.port}

# logging
logging:
  path: logs
  file: legion-agent
  level:
    org.springframework: info
    com.zcs.legion: info
    com.legion.client: info
    com.legion.net: info

#legion config
legion:
  module:
    group-id: agentdev
    #    group-id: 2019
    zipkinHttpHost: 172.16.1.145:9411
    notTrace: true
    link:
      host: 172.18.90.34
      port: 22104
      read-timeout-retry-times: 0
      timeout-retry-delay: -1
    heartbeat:
      interval-seconds: 5
  agent:
    tags:
      tsm: http://172.18.90.8:61614
      message: http://172.18.90.7:9083
      ZCAppcommon: http://172.80.80.42:8080
      ZCAms: http://172.18.90.7:10081