spring:
  application:
    name: legion-agent
  profiles:
    include:
      - tags

# server
server:
  port: 8802
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  connection-timeout: 5000
  servlet:
    context-path: /

# management
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      base-path: /exporter
      exposure:
        include: prometheus
    jmx:
      exposure:
        exclude: '*'
  server:
    port: 1${server.port}

# logging
logging:
  path: logs
  level:
    org.springframework: info
    com.zcs.legion: debug
    com.legion.client: debug
    com.legion.net: debug

#legion config
legion:
  net:
    serverUrls:
      - tcp://127.0.0.1:8850
    node:
      nodeId: m1-agents
      groupId: agent

  agent:
    tags:
      tsm: http://172.18.90.8:61614
      message: http://172.18.90.7:9083
      ZCAppcommon: http://172.80.80.42:8080
      ZCAms: http://172.18.90.7:10081