// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: a.proto

package com.zcs.legion.api;

public final class A {
  private A() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.zcs.legion.api.RequestType}
   */
  public enum RequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 内部服务请求
     * </pre>
     *
     * <code>IN = 0;</code>
     */
    IN(0),
    /**
     * <pre>
     *外部服务请求
     * </pre>
     *
     * <code>EXT = 1;</code>
     */
    EXT(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 内部服务请求
     * </pre>
     *
     * <code>IN = 0;</code>
     */
    public static final int IN_VALUE = 0;
    /**
     * <pre>
     *外部服务请求
     * </pre>
     *
     * <code>EXT = 1;</code>
     */
    public static final int EXT_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestType valueOf(int value) {
      return forNumber(value);
    }

    public static RequestType forNumber(int value) {
      switch (value) {
        case 0: return IN;
        case 1: return EXT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zcs.legion.api.A.getDescriptor().getEnumTypes().get(0);
    }

    private static final RequestType[] VALUES = values();

    public static RequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.zcs.legion.api.RequestType)
  }

  public interface BrokerMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zcs.legion.api.BrokerMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string body = 1;</code>
     */
    java.lang.String getBody();
    /**
     * <code>string body = 1;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();

    /**
     * <code>int32 code = 2;</code>
     */
    int getCode();

    /**
     * <pre>
     *请求服务类型
     * </pre>
     *
     * <code>.com.zcs.legion.api.RequestType requestType = 3;</code>
     */
    int getRequestTypeValue();
    /**
     * <pre>
     *请求服务类型
     * </pre>
     *
     * <code>.com.zcs.legion.api.RequestType requestType = 3;</code>
     */
    com.zcs.legion.api.A.RequestType getRequestType();

    /**
     * <pre>
     *如果请求服务类型是外部服务请求 则此字段必须有值
     * </pre>
     *
     * <code>string requestUrl = 4;</code>
     */
    java.lang.String getRequestUrl();
    /**
     * <pre>
     *如果请求服务类型是外部服务请求 则此字段必须有值
     * </pre>
     *
     * <code>string requestUrl = 4;</code>
     */
    com.google.protobuf.ByteString
        getRequestUrlBytes();

    /**
     * <pre>
     *请求类型 POST/GET
     * </pre>
     *
     * <code>string httpMethod = 5;</code>
     */
    java.lang.String getHttpMethod();
    /**
     * <pre>
     *请求类型 POST/GET
     * </pre>
     *
     * <code>string httpMethod = 5;</code>
     */
    com.google.protobuf.ByteString
        getHttpMethodBytes();
  }
  /**
   * Protobuf type {@code com.zcs.legion.api.BrokerMessage}
   */
  public  static final class BrokerMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zcs.legion.api.BrokerMessage)
      BrokerMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BrokerMessage.newBuilder() to construct.
    private BrokerMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BrokerMessage() {
      body_ = "";
      code_ = 0;
      requestType_ = 0;
      requestUrl_ = "";
      httpMethod_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BrokerMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              body_ = s;
              break;
            }
            case 16: {

              code_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              requestType_ = rawValue;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              requestUrl_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              httpMethod_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zcs.legion.api.A.internal_static_com_zcs_legion_api_BrokerMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zcs.legion.api.A.internal_static_com_zcs_legion_api_BrokerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zcs.legion.api.A.BrokerMessage.class, com.zcs.legion.api.A.BrokerMessage.Builder.class);
    }

    public static final int BODY_FIELD_NUMBER = 1;
    private volatile java.lang.Object body_;
    /**
     * <code>string body = 1;</code>
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      }
    }
    /**
     * <code>string body = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private int code_;
    /**
     * <code>int32 code = 2;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int REQUESTTYPE_FIELD_NUMBER = 3;
    private int requestType_;
    /**
     * <pre>
     *请求服务类型
     * </pre>
     *
     * <code>.com.zcs.legion.api.RequestType requestType = 3;</code>
     */
    public int getRequestTypeValue() {
      return requestType_;
    }
    /**
     * <pre>
     *请求服务类型
     * </pre>
     *
     * <code>.com.zcs.legion.api.RequestType requestType = 3;</code>
     */
    public com.zcs.legion.api.A.RequestType getRequestType() {
      @SuppressWarnings("deprecation")
      com.zcs.legion.api.A.RequestType result = com.zcs.legion.api.A.RequestType.valueOf(requestType_);
      return result == null ? com.zcs.legion.api.A.RequestType.UNRECOGNIZED : result;
    }

    public static final int REQUESTURL_FIELD_NUMBER = 4;
    private volatile java.lang.Object requestUrl_;
    /**
     * <pre>
     *如果请求服务类型是外部服务请求 则此字段必须有值
     * </pre>
     *
     * <code>string requestUrl = 4;</code>
     */
    public java.lang.String getRequestUrl() {
      java.lang.Object ref = requestUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *如果请求服务类型是外部服务请求 则此字段必须有值
     * </pre>
     *
     * <code>string requestUrl = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRequestUrlBytes() {
      java.lang.Object ref = requestUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HTTPMETHOD_FIELD_NUMBER = 5;
    private volatile java.lang.Object httpMethod_;
    /**
     * <pre>
     *请求类型 POST/GET
     * </pre>
     *
     * <code>string httpMethod = 5;</code>
     */
    public java.lang.String getHttpMethod() {
      java.lang.Object ref = httpMethod_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        httpMethod_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *请求类型 POST/GET
     * </pre>
     *
     * <code>string httpMethod = 5;</code>
     */
    public com.google.protobuf.ByteString
        getHttpMethodBytes() {
      java.lang.Object ref = httpMethod_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        httpMethod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getBodyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, body_);
      }
      if (code_ != 0) {
        output.writeInt32(2, code_);
      }
      if (requestType_ != com.zcs.legion.api.A.RequestType.IN.getNumber()) {
        output.writeEnum(3, requestType_);
      }
      if (!getRequestUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, requestUrl_);
      }
      if (!getHttpMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, httpMethod_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getBodyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, body_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, code_);
      }
      if (requestType_ != com.zcs.legion.api.A.RequestType.IN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, requestType_);
      }
      if (!getRequestUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, requestUrl_);
      }
      if (!getHttpMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, httpMethod_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zcs.legion.api.A.BrokerMessage)) {
        return super.equals(obj);
      }
      com.zcs.legion.api.A.BrokerMessage other = (com.zcs.legion.api.A.BrokerMessage) obj;

      boolean result = true;
      result = result && getBody()
          .equals(other.getBody());
      result = result && (getCode()
          == other.getCode());
      result = result && requestType_ == other.requestType_;
      result = result && getRequestUrl()
          .equals(other.getRequestUrl());
      result = result && getHttpMethod()
          .equals(other.getHttpMethod());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + REQUESTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + requestType_;
      hash = (37 * hash) + REQUESTURL_FIELD_NUMBER;
      hash = (53 * hash) + getRequestUrl().hashCode();
      hash = (37 * hash) + HTTPMETHOD_FIELD_NUMBER;
      hash = (53 * hash) + getHttpMethod().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zcs.legion.api.A.BrokerMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zcs.legion.api.A.BrokerMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zcs.legion.api.A.BrokerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zcs.legion.api.A.BrokerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zcs.legion.api.A.BrokerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zcs.legion.api.A.BrokerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zcs.legion.api.A.BrokerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zcs.legion.api.A.BrokerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zcs.legion.api.A.BrokerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zcs.legion.api.A.BrokerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zcs.legion.api.A.BrokerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zcs.legion.api.A.BrokerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zcs.legion.api.A.BrokerMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zcs.legion.api.BrokerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zcs.legion.api.BrokerMessage)
        com.zcs.legion.api.A.BrokerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zcs.legion.api.A.internal_static_com_zcs_legion_api_BrokerMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zcs.legion.api.A.internal_static_com_zcs_legion_api_BrokerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zcs.legion.api.A.BrokerMessage.class, com.zcs.legion.api.A.BrokerMessage.Builder.class);
      }

      // Construct using com.zcs.legion.api.A.BrokerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        body_ = "";

        code_ = 0;

        requestType_ = 0;

        requestUrl_ = "";

        httpMethod_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zcs.legion.api.A.internal_static_com_zcs_legion_api_BrokerMessage_descriptor;
      }

      @java.lang.Override
      public com.zcs.legion.api.A.BrokerMessage getDefaultInstanceForType() {
        return com.zcs.legion.api.A.BrokerMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.zcs.legion.api.A.BrokerMessage build() {
        com.zcs.legion.api.A.BrokerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zcs.legion.api.A.BrokerMessage buildPartial() {
        com.zcs.legion.api.A.BrokerMessage result = new com.zcs.legion.api.A.BrokerMessage(this);
        result.body_ = body_;
        result.code_ = code_;
        result.requestType_ = requestType_;
        result.requestUrl_ = requestUrl_;
        result.httpMethod_ = httpMethod_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zcs.legion.api.A.BrokerMessage) {
          return mergeFrom((com.zcs.legion.api.A.BrokerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zcs.legion.api.A.BrokerMessage other) {
        if (other == com.zcs.legion.api.A.BrokerMessage.getDefaultInstance()) return this;
        if (!other.getBody().isEmpty()) {
          body_ = other.body_;
          onChanged();
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (other.requestType_ != 0) {
          setRequestTypeValue(other.getRequestTypeValue());
        }
        if (!other.getRequestUrl().isEmpty()) {
          requestUrl_ = other.requestUrl_;
          onChanged();
        }
        if (!other.getHttpMethod().isEmpty()) {
          httpMethod_ = other.httpMethod_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zcs.legion.api.A.BrokerMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zcs.legion.api.A.BrokerMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object body_ = "";
      /**
       * <code>string body = 1;</code>
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string body = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string body = 1;</code>
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string body = 1;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>string body = 1;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        body_ = value;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 2;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 2;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 2;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private int requestType_ = 0;
      /**
       * <pre>
       *请求服务类型
       * </pre>
       *
       * <code>.com.zcs.legion.api.RequestType requestType = 3;</code>
       */
      public int getRequestTypeValue() {
        return requestType_;
      }
      /**
       * <pre>
       *请求服务类型
       * </pre>
       *
       * <code>.com.zcs.legion.api.RequestType requestType = 3;</code>
       */
      public Builder setRequestTypeValue(int value) {
        requestType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求服务类型
       * </pre>
       *
       * <code>.com.zcs.legion.api.RequestType requestType = 3;</code>
       */
      public com.zcs.legion.api.A.RequestType getRequestType() {
        @SuppressWarnings("deprecation")
        com.zcs.legion.api.A.RequestType result = com.zcs.legion.api.A.RequestType.valueOf(requestType_);
        return result == null ? com.zcs.legion.api.A.RequestType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *请求服务类型
       * </pre>
       *
       * <code>.com.zcs.legion.api.RequestType requestType = 3;</code>
       */
      public Builder setRequestType(com.zcs.legion.api.A.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        requestType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求服务类型
       * </pre>
       *
       * <code>.com.zcs.legion.api.RequestType requestType = 3;</code>
       */
      public Builder clearRequestType() {
        
        requestType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object requestUrl_ = "";
      /**
       * <pre>
       *如果请求服务类型是外部服务请求 则此字段必须有值
       * </pre>
       *
       * <code>string requestUrl = 4;</code>
       */
      public java.lang.String getRequestUrl() {
        java.lang.Object ref = requestUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *如果请求服务类型是外部服务请求 则此字段必须有值
       * </pre>
       *
       * <code>string requestUrl = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRequestUrlBytes() {
        java.lang.Object ref = requestUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *如果请求服务类型是外部服务请求 则此字段必须有值
       * </pre>
       *
       * <code>string requestUrl = 4;</code>
       */
      public Builder setRequestUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *如果请求服务类型是外部服务请求 则此字段必须有值
       * </pre>
       *
       * <code>string requestUrl = 4;</code>
       */
      public Builder clearRequestUrl() {
        
        requestUrl_ = getDefaultInstance().getRequestUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *如果请求服务类型是外部服务请求 则此字段必须有值
       * </pre>
       *
       * <code>string requestUrl = 4;</code>
       */
      public Builder setRequestUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object httpMethod_ = "";
      /**
       * <pre>
       *请求类型 POST/GET
       * </pre>
       *
       * <code>string httpMethod = 5;</code>
       */
      public java.lang.String getHttpMethod() {
        java.lang.Object ref = httpMethod_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          httpMethod_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *请求类型 POST/GET
       * </pre>
       *
       * <code>string httpMethod = 5;</code>
       */
      public com.google.protobuf.ByteString
          getHttpMethodBytes() {
        java.lang.Object ref = httpMethod_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          httpMethod_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *请求类型 POST/GET
       * </pre>
       *
       * <code>string httpMethod = 5;</code>
       */
      public Builder setHttpMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        httpMethod_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求类型 POST/GET
       * </pre>
       *
       * <code>string httpMethod = 5;</code>
       */
      public Builder clearHttpMethod() {
        
        httpMethod_ = getDefaultInstance().getHttpMethod();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求类型 POST/GET
       * </pre>
       *
       * <code>string httpMethod = 5;</code>
       */
      public Builder setHttpMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        httpMethod_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zcs.legion.api.BrokerMessage)
    }

    // @@protoc_insertion_point(class_scope:com.zcs.legion.api.BrokerMessage)
    private static final com.zcs.legion.api.A.BrokerMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zcs.legion.api.A.BrokerMessage();
    }

    public static com.zcs.legion.api.A.BrokerMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BrokerMessage>
        PARSER = new com.google.protobuf.AbstractParser<BrokerMessage>() {
      @java.lang.Override
      public BrokerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BrokerMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BrokerMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BrokerMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zcs.legion.api.A.BrokerMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zcs_legion_api_BrokerMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zcs_legion_api_BrokerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\007a.proto\022\022com.zcs.legion.api\"\211\001\n\rBroker" +
      "Message\022\014\n\004body\030\001 \001(\t\022\014\n\004code\030\002 \001(\005\0224\n\013r" +
      "equestType\030\003 \001(\0162\037.com.zcs.legion.api.Re" +
      "questType\022\022\n\nrequestUrl\030\004 \001(\t\022\022\n\nhttpMet" +
      "hod\030\005 \001(\t*\036\n\013RequestType\022\006\n\002IN\020\000\022\007\n\003EXT\020" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_zcs_legion_api_BrokerMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zcs_legion_api_BrokerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zcs_legion_api_BrokerMessage_descriptor,
        new java.lang.String[] { "Body", "Code", "RequestType", "RequestUrl", "HttpMethod", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
